src/components/ChoiceSlide/ChoiceSlide.tsx
src/components/ChoiceSlider/ChoiceSlider.tsx
src/components/TopicCard/TopicCard.styles.tsx
src/components/TopicCard/TopicCard.tsx
src/interfaces/api/topic.ts

ChoiceSlider를 TopicCard로 부터 위와 같이 분리했습니다
> Such a beautiful code!..

fix: separatea ChoiceSlider from TopicCard

---

index.html
src/assets/styles/global.tsx

fix: move font declaration to index.html

---

index.html

HTML title 수정
> AB - 세상의 모든 질문, AB로 답하다

fix: html title

---

src/components/Home/ChoiceSlide/ChoiceSlide.tsx

fix: text top

---

src/apis/fetch.ts
src/apis/topic/useTopics.ts
src/components/Home/ChoiceSlider/ChoiceSlider.tsx
src/components/Home/TopicCard/TopicCard.styles.tsx
src/components/Home/TopicCard/TopicCard.tsx
src/interfaces/api/error.ts
src/interfaces/api/index.ts
src/interfaces/api/topic.ts
src/routes/Home/Home.tsx
src/routes/index.tsx

2023.12.29 21:00 - CORS 오류 발생으로 draft 처리 해두겠음

feat: 토픽 조회 API 요청 구현

---

src/components/Home/ChoiceSlide/ChoiceSlide.styles.tsx
src/components/Home/ChoiceSlide/ChoiceSlide.tsx
src/components/Home/ChoiceSlider/ChoiceSlider.tsx
src/components/Home/TopicCard/TopicCard.styles.tsx
src/components/Home/TopicCard/TopicCard.tsx
src/components/Home/VoteCompletion/VoteCompletion.styles.tsx
src/interfaces/api/topic.ts
src/utils/screenWidth.ts

https://github.com/team-offonoff/web/assets/26860466/c4574d2d-4964-4df7-94c9-c685004422ae
ChoiceSlide의 길이를 수정했습니다.
이외에도 배경에 있는 A, B 텍스트의 위치도 수정했습니다.
Closes #100

fix: choice slide background text top

---

src/apis/topic/useTopics.ts
src/apis/topic/useVoteTopic.ts
src/components/Home/Comment/Comment.tsx
src/components/Home/CommentBox/CommentBox.tsx
src/components/Home/TopicCard/TopicCard.tsx
src/interfaces/api/comment.ts
src/interfaces/api/topic.ts
tsconfig.paths.json

- 투표 후 요청이 성공하면 결과가 반영되어 VoteCompletetion가 보이도록 수정
- 서버에서 unix 시간대로 바뀐거 반영
- 댓글 작성 n분전, n시간전, n일전 기준 수정

feat: 투표 후 결과 반영되도록 수정

---

src/apis/comment/useComment.ts
src/components/Home/TopicCard/TopicCard.tsx

feat: add latest comment when topic card loaded

---

src/assets/styles/theme.ts
src/components/commons/TextInput/TextInput.styles.tsx
src/components/commons/TextInput/TextInput.tsx
src/routes/Auth/signup/정보입력.tsx

fix: TextInput 에러 수정

---

src/components/commons/InputField/InputField.tsx
src/components/commons/Layout/Layout.styles.tsx
src/components/commons/TextInput/TextInput.styles.tsx
src/components/commons/TextInput/TextInput.tsx
src/constants/form.ts
src/routes/Auth/signup/Signup.tsx
src/routes/Auth/signup/정보입력.styles.tsx
src/routes/Auth/signup/정보입력.tsx

https://github.com/team-offonoff/web/assets/26860466/b0ff09e2-529d-497f-855c-052b524fb03f
- 입력 시 `/` 추가는 useEffect에서 구현
```typescript
useEffect(() => {
if (birthdayInput?.length === 4 || birthdayInput?.length === 7) {
methods.setValue(INPUT_TYPE.BIRTHDAY, birthdayInput + '/');
}
}, [birthdayInput, methods]);
```
- 글자 삭제 시 `/` 지워지는건 onKeyDown으로 구현
```typescript
const handleBirthdayInputKeyDown = (e: React.KeyboardEvent<HTMLInputElement>) => {
if (e.key === 'Backspace' && (birthdayInput?.length === 6 || birthdayInput?.length === 9)) {
methods.setValue(INPUT_TYPE.BIRTHDAY, birthdayInput.slice(0, -2));
}
if (e.key === 'Backspace' && (birthdayInput?.length === 5 || birthdayInput?.length === 8)) {
methods.setValue(INPUT_TYPE.BIRTHDAY, birthdayInput.slice(0, -1));
}
};
```

feat: 생년월일 입력

---

src/assets/styles/theme.ts
src/components/commons/RadioInput/RadioInput.tsx
src/constants/form.ts
src/routes/Auth/signup/정보입력.tsx

- RadioInput을 구현하고 정보입력 화면에 추가했습니다.

feat: 성별 입력 필드 추가

---

src/assets/icons/down-chevron.svg
src/assets/icons/index.ts
src/components/commons/RadioInput/RadioInput.tsx
src/components/commons/SelectInput/SelectInput.tsx
src/constants/form.ts
src/constants/signup.ts
src/routes/Auth/signup/정보입력.tsx

feat: 직업 선택 필드 추가

---

src/App.tsx
src/apis/comment/useComment.ts
src/apis/fetch.ts
src/components/Home/TopicCard/TopicCard.tsx

- 투표하지 않은 상태에서 latestComment 조회가 되고 있던 문제
- 개발 환경에서 시작 시 테스트를 위해 1~20번 토픽 투표 취소하도록 했음

fix: 투표 취소 에러 대응

---

src/components/Home/TopicCard/TopicCard.tsx

토픽 카드를 넘길 때마다 params가 변경되도록 변경

feat: change searchParams on change topic

---

src/App.tsx
src/apis/fetch.ts
src/components/Home/CommentBox/CommentBox.styles.tsx
src/components/commons/Text/Text.tsx
src/routes/Auth/login/Login.tsx

prop error 완벽하게 해결했습니다.
투표 취소 api가 오류나는 이유는 delete 메소드에 body가 있어서 그런거 같음.
서버에 수정 요청 했음.

fix: prop not recognizable

---

src/components/commons/TextInput/TextInput.styles.tsx
src/components/commons/TextInput/theme.ts
src/routes/Auth/signup/Signup.tsx
src/routes/Topic/BTopicCreate.tsx

- input theme2, 3의 placeholder 속성이 디자인 시안과 일치하지 않는 문제를 해결했습니다.
- Closes #152
- 작업한 내용 적어주세요

Input Theme 디자인 불일치 수정

---

.github/workflows/cd.yml

fix: remove enable option

---

src/apis/topic/useTopics.ts

fix: api url

---

src/components/Home/ChoiceSlide/ChoiceSlide.tsx
src/components/Home/TopicCard/TopicCard.tsx

- choice slide, topic title ui 조정
- choice slide, topic title을 글자수, 띄어쓰기에 따라 ui가 조정되도록 변경하였습니다
#

글자수,띄어쓰기에 따른 ui 조정

---

src/components/Home/TopicSwiper/TopicSlide.tsx
src/components/Home/TopicSwiper/TopicSwiper.tsx

- SwiperSlide가 SwiperWrapper 안에 들어가지 않는 이슈가 있었습니다.
- https://github.com/nolimits4web/swiper/issues/4413
- 위의 이슈가 있어서 displayName 지정하여 해결했음

feat: separate TopicSlide from swiper

---

src/components/Home/TopicCard/TopicCard.styles.tsx
src/components/Home/TopicCard/TopicCard.tsx
src/components/Home/TopicSwiper/TopicSwiper.tsx

- 무슨 목적/이유로 구현했는지
- Closes #number
- 작업한 내용 적어주세요

0.0.8v deploy

---

src/assets/styles/global.tsx
src/components/A/ATopicCard.tsx
src/components/B/BTopicCard.styles.tsx
src/components/B/BTopicCard.tsx
src/components/B/BTopicChoice.tsx
src/components/commons/BottomNavigation/BottomNavigation.tsx
src/components/commons/Chip/CommentChip.tsx
src/components/commons/Layout/Layout.styles.tsx
src/routes/A/ATopics.tsx
src/routes/B/BTopics.styles.tsx
src/routes/B/BTopics.tsx
src/routes/index.tsx

- B 사이드 화면 구현했습니다.
- Closes #number
- layout이 body의 backgroundColor를 inherit하도록 구현했습니다.

feat: B 사이드 토픽 홈 화면 구현

---

src/components/commons/Loading/Loading.tsx
src/routes/Auth/kakao/KakaoLogin.tsx

- KakaoLogin에 임시로 구현해둔 Loading 컴포넌트를 분리했습니다.

Loading 화면 분리

---

src/components/B/BTopicCard.tsx
src/components/Home/ChoiceSlide/ChoiceSlide.styles.tsx
src/components/commons/Header/BackButton/BackButton.tsx
src/components/commons/Loading/Loading.tsx
src/routes/Auth/kakao/KakaoLogin.tsx
src/routes/B/BTopic.tsx
src/routes/index.tsx

- B 사이드 화면에서 카드를 클릭했을 때 상세 화면을 보여주는 기능을 구현했습니다.
- Closes #161 
- 공용으로 사용할 수 있는 BackButton을 구현했습니다.

B 사이드 상세 페이지 구현

---

package.json
src/components/Home/CommentBox/CommentBox.tsx
src/main.tsx
yarn.lock

feat: add @sentry/react

---

src/components/commons/Button/DefaultButton.tsx
src/components/commons/RadioInput/RadioInput.tsx
src/routes/Auth/signup/Signup.styles.tsx
src/routes/Auth/signup/Signup.tsx
src/routes/Auth/signup/Terms.tsx

- signup 화면에서 하단 버튼을 DefaultButton으로 교체하여 디자인 불일치를 수정했습니다.
- Closes #167 
- 약관동의 후 홈화면으로 이동하게끔 했음

fix: signup 화면 디자인 불일치 수정

---

src/apis/oauth/index.ts
src/components/Login/LoginButton.tsx
src/hooks/useOAuth/useOAuth.ts
src/routes/Auth/google/GoogleLogin.tsx
src/routes/Auth/kakao/KakaoLogin.tsx
src/routes/Auth/login/Login.tsx

fix: admin login button

---

src/apis/oauth/index.ts
src/hooks/useOAuth/useOAuth.ts
src/routes/Auth/google/GoogleLogin.tsx
src/routes/Auth/kakao/KakaoLogin.tsx
src/routes/Auth/login/Login.tsx

- 구글 로그인 기능을 추가했습니다
- Closes #171
- useOAuth 구현해서 KakaoLogin, GoogleLogin 구현부를 단순하게 만들었습니다

fix: google oauth 로그인 구현

---

package.json
src/App.tsx
src/assets/styles/theme.ts
src/components/Home/ChoiceSlider/ChoiceSlider.tsx
src/components/Home/TopicCard/TopicCard.tsx
src/components/commons/Toast/Toast.tsx
src/interfaces/styled.d.ts
src/routes/B/BTopic.tsx
yarn.lock

- 본인이 작성한 토픽에 투표 시 투표 동작 취소
- Closes #173 
- Toast 추가했습니다.
- `Toast.error('메시지')` 로 사용하면 돼요

fix: 토픽 작성자는 투표 불가

---

src/components/B/BTopicCard.tsx
src/components/Home/TopicCard/TopicCard.styles.tsx
src/components/TopicCreate/TopicCreateTextInput.tsx
src/hooks/useModal/useActionSheet.tsx
src/routes/A/ATopics.tsx
src/routes/Auth/signup/Signup.tsx
src/routes/B/BTopics.tsx
src/routes/MyPage/ModifyProfile/ModifyProfile.tsx
src/routes/Topic/Create/ASide/ATopicCreate.tsx
src/routes/Topic/Create/BSide/BTopicCreateStep1.tsx

- B 토픽에서 진행중/종료된을 비롯한 최신순/내토픽만 필터를 searchParams로 관리하여 B 토픽 상세 페이지를 들어갔다가 나와도 필터 상태를 유지할 수 있도록 구현했습니다.

feat: filter topics with 진행중/종료된

---

src/apis/topic/useTopics.ts
src/assets/icons/dot.svg
src/assets/icons/index.ts
src/components/TopicCreate/ImageInputComponent.tsx
src/components/TopicCreate/TopicCreateImageInput.tsx
src/components/commons/Button/TopicCreateButton.tsx
src/constants/form.ts
src/routes/MyPage/MyPage.tsx
src/routes/Topic/Create/ASide/ATopicCreate.tsx
src/routes/Topic/Create/BSide/BTopicCreate.tsx
src/routes/Topic/Create/BSide/BTopicCreateStep1.tsx
src/routes/Topic/Create/TopicCreate.tsx

- 토픽생성 - 이미지 업로드 추가, 버튼 디자인 변경 추가
- 토픽생성 이미지 기능 추가
- 토픽생성 버튼으로 변경

토픽생성 - 이미지 업로드 추가, 버튼 디자인 변경 추가

---

src/routes/MyPage/MyPage.tsx
src/routes/index.tsx

- 로그아웃 기능을 구현했습니다
- Closes #227
- routes에서 Outlet을 분기 처리로 렌더링하여 호출 시점이 늦어지는 문제를 개선함

로그아웃 기능 구현

---

index.html

- 배포 후 사용자가 최신화된 배포 버전을 받아볼 수 있도록 meta 태그를 추가했습니다.
- Closes #242 
- 작업한 내용 적어주세요

캐시 무효화(cache busting)

---

src/components/A/ATopicCard.tsx

- ATopicCard에 useActionSheet 추가

feat: add topic card action sheet
