team-offonoff/web

src/assets/styles/theme.ts
src/components/Home/CommentBox/CommentBox.styles.tsx
src/components/Home/CommentBox/CommentBox.tsx
src/components/Home/TopicCard/TopicCard.tsx
src/components/commons/BottomSheet/BottomSheet.tsx
src/components/commons/Layout/Layout.styles.tsx
src/routes/Home/Home.tsx

https://github.com/team-offonoff/web/assets/26860466/2c19e8b1-6e7a-4389-85ed-1e0f53761746
댓글 바텀시트를 구현했습니다.
추후 댓글 영역 구현하면서 사이드 이펙트 발견 시 바텀시트 쭉 손봐야 할 것으로 예상됨
인터페이스는 아래와 같음
```
interface BottomSheetProps {
open: boolean;
setIsOpen: React.Dispatch<React.SetStateAction<boolean>>;
snapPoints?: number[];
initialSnap?: number;
children: React.ReactNode;
}
```
`setIsOpen` 대신에 `closeSheet` 사용하는 것은 어떤지

댓글 바텀시트 구현

---

src/apis/fetch.ts
src/hooks/useFunnel/useFunnel.tsx
src/interfaces/api/index.ts
src/routes/Auth/kakao/KakaoLogin.tsx
src/routes/Auth/signup/Signup.tsx

closes #88 
```typescript
const data = await response.json();
if (!response.ok) {
throw new ResponseError(data);
}
return data as TData;
```
이제 fetch.post를 사용할 때 에러가 response가 ok가 아니라면(=200~299) `ResponseError`를 throw합니다.
이 에러를 던지는 fetch를 사용하는 쪽에서는 이렇게 에러 핸들링을 하면 됩니다.
```typescript
try {
const response = await kakaoLogin(kakaoCode);
if (response && response.accessToken) {
response.newMember ? navigate('/onboard') : navigate('/');
}
} catch (err) {
if (err instanceof ResponseError) {
if (err.errorData.abCode === 'ILLEGAL_JOIN_STATUS') {
navigate(`/signup`, { state: { memberId: err.errorData.errorContent.payload } });
}
}
}
```
저 에러 코드 `ILLEGAL_JOIN_STATUS`는 enum이나 상수로 관리해야할 필요가 보이네요
다음 PR 때 반영하겠습니다.

feat: add ResponseError class

---

src/components/Home/TopicCard/TopicCard.tsx
src/components/commons/BottomSheet/BottomSheet.tsx
src/hooks/useBottomSheet/useBottomSheet.tsx

BottomSheet을 개선했습니다
1. useBottomSheet hooks로 BottomSheet를 선언적으로 사용할 수 있게 변경
BottomSheet를 사용할 때 마다 이 BottomSheet를 열고 닫기 위한 상태, 조건부 렌더링을 구현했었는데, 이 구현부를 useBottomSheet로 숨겼습니다.
```typescript
const { BottomSheet: CommentSheet, toggleSheet } = useBottomSheet({});
```
2. BackDrop 영역의 zindex를 수정하여 더 이상 백드롭 영역을 클릭했을 때 바탕의 요소가 클릭되지 않습니다.

feat: better bottomsheet

---

src/components/Home/TopicCard/TopicCard.tsx

`dev` 병합 과정에서 TopicCard에 적용된 useBottomSheet가 누락된 문제가 있었습니다.
이를 해결하는 hotfix PR입니다.

fix: replace to useBottomSheet

---

package.json
src/apis/comment/useComment.ts
src/apis/fetch.ts
src/assets/icons/index.ts
src/assets/icons/report.svg
src/assets/styles/theme.ts
src/components/Home/ChoiceSlider/ChoiceSlider.tsx
src/components/Home/Comment/Comment.tsx
src/components/Home/Comment/Thumbs.tsx
src/components/Home/TopicCard/TopicCard.tsx
src/components/commons/Modal/Modal.tsx
src/interfaces/api/comment.ts
yarn.lock

- `useComments` infinitequery 추가
- 현재 페이지의 마지막 댓글이 화면에 보이는 순간 `fetchNextPage` 호출하는 작업 필요함
- 댓글 좋아요/싫어요 눌렀을 때 mutation 하는 작업 필요함

feat: 댓글 조회 API 연동

---

src/App.tsx
src/components/Home/TopicCard/TopicCard.tsx
src/components/Home/TopicComments/TopicComments.styles.tsx
src/components/Home/TopicComments/TopicComments.tsx
src/components/commons/BottomSheet/BottomSheet.tsx
src/components/commons/Flex/Flex.tsx
src/components/commons/Portal/Portal.tsx
src/components/commons/Text/Text.tsx

댓글 바텀시트 UI 구현했습니다.
- 이제 `draggable`이 className에 포함되어 있어야 drag가 가능합니다
- 상단의 handleBar 부분은 기본적으로 draggable로 되어 있으며, botttomSheet의 자식 요소 중에서도 draggable를 className에 추가하면 됩니다
- 댓글 부분에만 데이터 바인딩되어 있습니다
NEXT TODO

fix: React does not recognize prop warning

---

src/apis/comment/useComment.ts
src/components/Home/Comment/Comment.tsx
src/components/Home/TopicCard/TopicCard.tsx
src/components/Home/TopicComments/TopicComments.tsx
src/interfaces/api/comment.ts

- 댓글 쓰기 기능 구현
- 댓글 좋아요/싫어요 반응 기능 구현
- Closes #107
- Closes #108
- 댓글 좋아요/싫어요 API의 응답으로부터 queryData를 클라이언트에서 수동으로 변경하는 방식으로 구현했습니다.
- 이는 이후 댓글의 개수가 늘어날 시 서버로부터 fetch 받아 다시 데이터를 설정하는 오버헤드를 방지하기 위함입니다.
- infiniteQueryData 변경하느라 힘들었습니다.
```typescript
onSuccess: (data: CommentReaction) => {
queryClient.setQueryData(
[COMMENT_KEY, topicId],
(oldData: InfiniteData<PagingDataResponse<CommentResponse>, unknown> | undefined) => {
if (!oldData) return oldData;
return {
...oldData,
pages: oldData.pages.map((page) => {
return {
...page,
data: page.data.map((comment) =>
comment.commentId === commentId ? { ...comment, commentReaction: data } : comment
),
};
}),
};
}
);
},
```
- 크롬에서 댓글 쓰기 시 마지막 글자가 포함되어 두 번 요청되는 이슈가 있습니다. 추후 수정 예정

feat: 댓글 등록 및 댓글 좋아요/싫어요

---

src/apis/topic/useVoteTopic.ts
src/components/Home/ChoiceSlider/ChoiceSlider.tsx
src/components/Home/CommentBox/CommentBox.tsx
src/components/Home/TopicCard/TopicCard.tsx
src/interfaces/api/comment.ts

topicCard에 voteMutation를 추가했습니다.
- `useVoteTopic`에서 onSuccess 시 useTopics invalidate 또는 setQueryData로 selectedOption 직접 수정하는 작업 필요
- 만료되거나 토픽 작성자가 투표하는 경우에 대한 예외처리 필요

feat: 투표 api 연결

---

src/apis/oauth/signup.ts
src/components/commons/RadioInput/RadioInput.tsx
src/components/commons/SelectInput/SelectInput.tsx
src/components/commons/TextInput/TextInput.tsx
src/constants/form.ts
src/routes/Auth/signup/Signup.tsx
src/routes/Auth/signup/정보입력.tsx

`/auth/signup/profile`로 사용자 정보 입력하는 API를 연동했습니다.

feat: 회원가입 폼 api 연결

---

src/hooks/useFunnel/useFunnel.tsx
src/routes/Auth/kakao/KakaoLogin.tsx
src/routes/Auth/signup/Signup.tsx

`useFunnel`에서 searchParams 변경 시 현재 location의 state를 유지하도록 수정했습니다.
Closes #128 
```typescript
const setStep = useCallback(
(step: Steps[number]) => {
setSearchParams(
(searchParams) => {
searchParams.set('funnel-step', step);
return searchParams;
},
{
state: { ...location.state },
}
);
},
[setSearchParams]
);
```

fix: persist location when setSearchParams

---

src/components/Home/Comment/Thumbs.tsx
src/components/Login/LoginButton.tsx
src/routes/Auth/login/Login.styles.tsx
src/routes/Auth/login/Login.tsx

Login UI 수정

---

src/components/commons/Layout/Layout.styles.tsx
src/components/commons/Layout/Layout.tsx

- HeaderSection을 Grid 방식으로 display하도록 변경했습니다.
- `grid-template-columns: 1fr auto 1fr`로 설정하여 HeaderCenter가 있는 경우는 그 넓이만큼 영역을 확보하도록 했음

fix: display to grid

---

src/apis/comment/useComment.ts
src/apis/topic/useTopics.ts
src/components/Home/Comment/Comment.tsx
src/components/Home/TopicCard/TopicCard.styles.tsx
src/components/Home/TopicCard/TopicCard.tsx
src/components/Home/TopicComments/TopicComments.tsx
src/hooks/useBottomSheet/useBottomSheet.tsx

- useBottomSheet에서 Sheet을 useCallback으로 memoization하여 해결했습니다.
- Closes #165 
- isOpen을 의존성 배열로 설정하여 함수를 memoization함

fix: 바텀 시트 두 번 열리던거 수정

---

src/apis/topic/useTopics.ts
src/components/Home/CommentBox/CommentBox.tsx
src/components/Home/TopicCard/TopicCard.tsx
src/interfaces/api/topic.ts
src/routes/A/AlphaTopics.tsx

- /topic/info의 응답 중에 특정 필드가 nullable하게 변경되어 이를 예외처리하는 코드를 작성했습니다.
- Closes #182

fix: TopicCard nullable한 필드 예외처리 추가

---

src/apis/fetch.ts
src/constants/localStorage.ts
src/routes/Auth/kakao/KakaoLogin.tsx
src/routes/index.tsx
src/store/auth.ts

- 로그인 후 새로고침 시 인증 정보가 사라지던 문제를 해결했습니다.
- Closes #164 
- 인증 시 refreshToken은 persist한 localStorage에, 보안성이 중요한 accessToken은 in-memory에 저장하도록 구현했습니다.
- 새로고침 시 저장되어 있던 refreshToken을 불러와 토큰 재발급 요청을 하고, 응답이 오면 새 accessToken을 저장해 사용합니다.
- 이외의 refrehToken이 없거나 만료되어 재발급 요청이 실패하는 경우 login 화면으로 이동시킵니다

fix: 인증 로직 구현

---

src/apis/topic/useVoteTopic.ts
src/components/A/ATopicCard.tsx
src/components/commons/ProgressBar/ProgressBar.tsx
src/interfaces/api/topic.ts
src/routes/Home/Home.tsx

- 토픽 조회 응답 모델에 voteCount가 포함되어 이를 반영하는 PR입니다.
- Closes #189
- ATopicCard memoize
- ATopics에서 topicFilter, isMineOnly, isLatest 등에 의해 리렌더링될 경우가 많은데 ATopicCard 자체는 props가 변경될 일이 적으므로 memoize를 통해 최적화
- useTopics가 infiniteQuery가 됨에 따라 useVoteTopic의 onSuccess 부분을 수정했습니다.

feat: A topic 투표 응답 모델 수정

---

src/components/Home/TopicCard/TopicCard.styles.tsx
src/components/Home/TopicCard/TopicCard.tsx
src/components/Home/TopicSwiper/TopicSwiper.tsx

- 홈 화면에서 높이가 부족해 TopicCard를 전부 보여주지 못하는 이슈를 해결했습니다.
- 화면 높이와 TopicCard의 높이에 따라 하단에 margin-bottom을 동적으로 할당하도록 구현했습니다.
- Closes #170

feat: enable scroll when height is not enough

---

src/routes/index.tsx

- lazy load를 통한 성능 최적화
- route를 lazy하게 불러오도록 하여 성능을 개선했습니다.
- 예를 들어 A 사이드 화면을 불러올 때 다른 화면들은 당장 필요하지 않으므로 lazy하게 import하도록 작성했습니다.

feat: load routes lazily

---

src/apis/fetch.ts
src/components/Home/TopicCard/TopicCard.tsx
src/hooks/useOAuth/useOAuth.ts
src/utils/scrollLock.ts

- selectedOption이 null인 경우로만 처리해서 자신이 생성한 토픽의 댓글을 조회하지 못하는 이슈를 해결했습니다.
- Closes #216 
- useAuthStore의 memberId와 비교하여 자신이 생성한 토픽에 대해서 조회가 가능하도록 수정

fix: 유저가 작성한 토픽인 경우 조회 가능하도록 수정

---

src/apis/fetch.ts
src/apis/profile/useProfile.ts
src/components/commons/Modal/ActionModalButton.tsx
src/components/commons/SelectInput/SelectInput.tsx
src/components/commons/TextInput/TextInput.styles.tsx
src/components/commons/TextInput/theme.ts
src/interfaces/api/profile.ts
src/routes/Auth/signup/Signup.tsx
src/routes/MyPage/ModifyProfile/ModifyProfile.styles.tsx
src/routes/MyPage/ModifyProfile/ModifyProfile.tsx
src/routes/MyPage/MyPage.styles.tsx
src/routes/MyPage/MyPage.tsx
src/routes/index.tsx

- mypage 퍼블리싱 및 기능 구현
- #160 
- ui 구현
- 내정보수정 api 연동
-  서버측에서 로그아웃 api 미완료, 약관 내용 정리 미완료 등으로 인한 기능을 제외하고 마이페이지 개발 완료하였습니다.

mypage 퍼블리싱 및 기능 구현
